---
- name: Testing AAP
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:

  - debug:
      msg: "Hello: {{ ansible_facts.fqdn }}"

  - name: Sleep for 15 seconds and continue with play
    ansible.builtin.wait_for:
      timeout: 15
    delegate_to: localhost